find_program(CLANG_TIDY_EXE NAMES
    "clang-tidy-10.0"
    "clang-tidy-10"
    "clang-tidy-9.0"
    "clang-tidy-9"
    "clang-tidy-8.0"
    "clang-tidy-8"
    "clang-tidy-7.0"
    "clang-tidy-6.0"
    "clang-tidy")

if (CLANG_TIDY_EXE)
    option(CLANG_TIDY "Enable clang-tidy" ON)
    if (CLANG_TIDY)
        set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXE}")

        # The files generated by Qt will produce clang-tidy warnings. We generate a
        # dummy .clang-tidy file in the build directory that disables all checks
        # except for one that will never apply. This is necessary, because
        # otherwise clang-tidy will complain about no checks being enabled.
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/.clang-tidy" "Checks: '-*,llvm-twine-local'")
    endif()
else()
    message(WARNING "Could not find clang-tidy.")
endif()
